### ISSUE TITLE
No cargo version configured 

### ISSUE THREAD

**Issue by Ludea** [BlackDex/rust-musl#11]
Hi,

I get
```
error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
```
when using container with GHA:
```
jobs:
  build_container:
    runs-on: ubuntu-latest
    container: blackdex/rust-musl:aarch64-musl-stable-1.82.0
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
```
